# Generated by Django 5.1.4 on 2024-12-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhino_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('absorption_125hz', models.FloatField(default=0.0)),
                ('absorption_250hz', models.FloatField(default=0.0)),
                ('absorption_500hz', models.FloatField(default=0.0)),
                ('absorption_1000hz', models.FloatField(default=0.0)),
                ('absorption_2000hz', models.FloatField(default=0.0)),
                ('absorption_4000hz', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
    ]
