# Generated by Django 5.1.4 on 2024-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhino_app', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_per_absorber',
            field=models.FloatField(default=1.0),
        ),
    ]
